---
openapi: 3.0.0
info:
  title: Bets - Bets API
  version: 2.0.0
paths:
  "/api/bets":
    post:
      operationId: create-bet
      summary: Create Bet
      tags:
        - bets
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                homeTeamScore:
                  type: string
                awayTeamScore:
                  type: string
                championship:
                  type: string
                match:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: ''
          content:
            application/json:
              examples:
                bet:
                  value:
                    match: 1X-DC
                    email: joe@doe.com
                    championship: Uefa Champions League
                    awayTeamScore: '2'
                    homeTeamScore: '3'
