// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/apirator/apirator/controllers"
	"github.com/apirator/apirator/internal/apimock/adapter"
	"github.com/apirator/apirator/internal/apimock/usecase"
	"github.com/apirator/apirator/internal/k8s"
	"github.com/apirator/apirator/internal/openapi"
	"github.com/apirator/apirator/internal/resources"
	"github.com/getkin/kin-openapi/openapi3"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func newAPIMockReconciler(mgr manager.Manager) (*controllers.APIMockReconciler, error) {
	runtimeScheme := extractScheme(mgr)
	builder := resources.NewBuilder(runtimeScheme)
	client := extractClient(mgr)
	service := k8s.NewService(client)
	configMap := &usecase.ConfigMap{
		Builder: builder,
		Service: service,
	}
	deployment := &usecase.Deployment{
		Builder: builder,
		Service: service,
	}
	deploymentAvailability := &usecase.DeploymentAvailability{
		Service: service,
	}
	ingress := &usecase.Ingress{
		Builder: builder,
		Service: service,
	}
	ingressFinalizer := &usecase.IngressFinalizer{
		Service: service,
	}
	status := &usecase.Status{
		Service: service,
	}
	loader := openapi3.NewLoader()
	validator := openapi.NewValidator(loader)
	openAPIDefinition := &usecase.OpenAPIDefinition{
		Validator: validator,
		Service:   service,
	}
	usecaseService := &usecase.Service{
		Builder: builder,
		Service: service,
	}
	userCases := &adapter.UserCases{
		ConfigMap:              configMap,
		Deployment:             deployment,
		DeploymentAvailability: deploymentAvailability,
		Ingress:                ingress,
		IngressFinalizer:       ingressFinalizer,
		Status:                 status,
		OpenAPIDefinition:      openAPIDefinition,
		Service:                usecaseService,
	}
	factory := adapter.NewFactory(userCases, service)
	apiMockReconciler := controllers.NewAPIMockReconciler(factory)
	return apiMockReconciler, nil
}

// wire.go:

func extractScheme(mgr manager.Manager) *runtime.Scheme {
	return mgr.GetScheme()
}

func extractClient(mgr manager.Manager) client.Client {
	return mgr.GetClient()
}
