// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/apirator/apirator/controllers"
	"github.com/apirator/apirator/internal/apimock/adapter"
	"github.com/apirator/apirator/internal/apimock/status"
	"github.com/apirator/apirator/internal/apimock/usecase"
	"github.com/apirator/apirator/internal/k8s"
	"github.com/apirator/apirator/internal/resources"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

import (
	_ "k8s.io/client-go/plugin/pkg/client/auth"
)

// Injectors from wire.go:

func newAPIMockReconciler(mgr manager.Manager) (*controllers.APIMockReconciler, error) {
	runtimeScheme := extractScheme(mgr)
	builder := resources.NewBuilder(runtimeScheme)
	client := extractClient(mgr)
	service := k8s.NewService(client)
	configMap := &usecase.ConfigMap{
		Builder: builder,
		Service: service,
	}
	statusManager := &status.Manager{}
	openAPIDefinition := &usecase.OpenAPIDefinition{
		Manager: statusManager,
		Service: service,
	}
	deployment := &usecase.Deployment{
		Builder: builder,
		Service: service,
	}
	ingress := &usecase.Ingress{
		Builder: builder,
		Service: service,
	}
	usecaseService := &usecase.Service{
		Builder: builder,
		Service: service,
	}
	userCases := &adapter.UserCases{
		ConfigMap:         configMap,
		OpenAPIDefinition: openAPIDefinition,
		Deployment:        deployment,
		Ingress:           ingress,
		Service:           usecaseService,
	}
	factory := adapter.NewFactory(userCases, service)
	apiMockReconciler := controllers.NewAPIMockReconciler(factory)
	return apiMockReconciler, nil
}
