apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: contour
  name: contour-ingress
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: players-mock
              servicePort: 8000
            path: /test