# permissions for end users to view apimocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimock-viewer-role
rules:
- apiGroups:
  - apirator.io
  resources:
  - apimocks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apirator.io
  resources:
  - apimocks/status
  verbs:
  - get
