# permissions for end users to edit apimocks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimock-editor-role
rules:
- apiGroups:
  - apirator.io
  resources:
  - apimocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apirator.io
  resources:
  - apimocks/status
  verbs:
  - get
