name: "New Release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version you want to release."
        required: true

jobs:
  new-release:
    name: "Draft a new release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ github.event.inputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: Prepare release ${{ github.event.inputs.version }}
          author: GitHub <noreply@github.com>
          signoff: true

          title: Release version ${{ github.event.inputs.version }}
          body: |
            Hi @${{ github.actor }}!

            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the changelog and bumped the versions in the manifest files.

            Merging this PR will create a GitHub release.
          reviewers: ${{ github.actor }}
          base: master
          branch: release/${{ github.event.inputs.version }}
          delete-branch: true
